<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rs</string>
	</array>
	<key>name</key>
	<string>Rust</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\!?\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>keyword.other.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.module.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.rust</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(mod)\s+(\w+)</string>
			<key>name</key>
			<string>meta.module.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(fn)\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.rust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|\{</string>
			<key>name</key>
			<string>meta.function.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\bproc\b</string>
			<key>name</key>
			<string>storage.type.function.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\|(?!.*?//)(?=.*\|)</string>
			<key>end</key>
			<string>\|</string>
			<key>name</key>
			<string>meta.closure.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(struct)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.struct.rust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|\(|(?&lt;=\})</string>
			<key>name</key>
			<string>meta.struct.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.struct.block.rust</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>entity.name.class.rust</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(let)\s+(?=\S)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.let.rust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|\=</string>
			<key>name</key>
			<string>meta.let.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.static.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rust</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.rust</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(static)\s+(?:(mut)\s+)?(\w+)</string>
			<key>name</key>
			<string>meta.static.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(type)\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.type.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.rust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\=</string>
			<key>name</key>
			<string>meta.type.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(enum)\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.enum.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.rust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|\{</string>
			<key>name</key>
			<string>meta.enum.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(trait)\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.trait.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.rust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|\{</string>
			<key>name</key>
			<string>meta.trait.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(impl)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.impl.rust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|\{</string>
			<key>name</key>
			<string>meta.impl.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_parameter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>for</string>
					<key>name</key>
					<string>storage.type.impl.rust</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>entity.name.class.rust</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(for)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.rust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\{</string>
			<key>name</key>
			<string>meta.for.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bin\b</string>
					<key>name</key>
					<string>keyword.control.rust</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:crate|use)\b</string>
			<key>name</key>
			<string>keyword.other.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b=&gt;\b</string>
			<key>name</key>
			<string>keyword.other.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:false|true)\b</string>
			<key>name</key>
			<string>constant.language.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:self|super)\b|(?&lt;=^|\W)_(?=\W|$)</string>
			<key>name</key>
			<string>variable.language.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:break|continue|if|else|loop|match|return|while)\b|=&gt;</string>
			<key>name</key>
			<string>keyword.control.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:extern|priv|pub|unsafe)\b</string>
			<key>name</key>
			<string>storage.modifier.rust</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+\!</string>
			<key>name</key>
			<string>support.function.rust</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.rust</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\*/</string>
					<key>name</key>
					<string>comment.block.documentation.rust</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.rust</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.rust</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.rust</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(///).*$</string>
					<key>name</key>
					<string>comment.line.double-slash.documentation.rust</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.rust</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$</string>
					<key>name</key>
					<string>comment.line.double-slash.rust</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.rust</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.rust</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+)?\.\.(\d+)</string>
					<key>name</key>
					<string>meta.range.rust</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.rust</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.rust</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;!\.)\b(0(?:b[01_]+|o[0-7_]+|x[\h_]+)|\d[\d_]*)((?:u|i)(?:8|16|32|64))?\b(?!\.)</string>
					<key>name</key>
					<string>meta.numeric.rust</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.rust</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.rust</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;!\.)\b(\d[\d_]*(?:\.[\d_]+)?(?:[eE][\+\-]?[\d\_]+)?)(f(?:32|64))?\b(?!\.)</string>
					<key>name</key>
					<string>meta.numeric.rust</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.?\b_?\d\S*\b[\.\+\-]?</string>
					<key>name</key>
					<string>invalid.illegal.numeric.rust</string>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>variable.parameter.rust</string>
				</dict>
			</array>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(?:[\\\"'nrt0]|U\h{8}|u\h{4}|x\h{2})</string>
					<key>name</key>
					<string>constant.character.escape.rust</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\ |\\.[^"'\s]*</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.rust</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>r(\#*)\"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rust</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\1</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rust</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.other.rust</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rust</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rust</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rust</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rust</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rust</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rust</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:(?&lt;=')(?:[^'\n]{2,})|^[^'\n]+)</string>
							<key>name</key>
							<string>invalid.illegal.character.rust</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type_parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\&lt;)\&lt;(?!\&lt;)</string>
					<key>end</key>
					<string>\&gt;</string>
					<key>name</key>
					<string>meta.type.generic.rust</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>support.type.rust</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\'\w+(?!\')\b</string>
					<key>name</key>
					<string>storage.type.rust</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:\b[A-Z]\w*|(?&lt;=^|\W)\!(?=\W|$)|\b(?:bool|int|uint|u8|u16|u32|u64|i8|i16|i32|i64|f32|f64|char|str)\b)</string>
					<key>name</key>
					<string>storage.type.rust</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:as|box|mut|ref)\b|&amp;(?=[\w'])</string>
					<key>name</key>
					<string>keyword.operator.rust</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_parameter</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rust</string>
	<key>uuid</key>
	<string>ebcf1365-829d-4af2-aa0e-df7e588b08a3</string>
</dict>
</plist>
